version: '2.1'
services:
  database:
    image: 'mysql:latest'
    container_name: dev.api.db
    environment:
      MYSQL_ROOT_PASSWORD: sam
      MYSQL_DATABASE: sam
      MYSQL_USER: sam
      MYSQL_PASSWORD: sam
    ports:
      - '3306:3306'
    healthcheck:
      test: '/usr/bin/mysql --user=sam --password=sam --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 20s
      retries: 10
