AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-devops-test-app-1

  DevOps test 1 SAM app based on Sample SAM Template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          DB_SERVER_HOST: aws-rds-cluster-endpoint
      Events:
        HelloWorldGET:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        HelloWorldPUT:
          Type: Api
          Properties:
            Path: /hello
            Method: put
        HelloWorldGET2:
          Type: Api
          Properties:
            Path: /hello/{proxy+}
            Method: get
        HelloWorldPUT2:
          Type: Api
          Properties:
            Path: /hello/{proxy+}
            Method: put
      AutoPublishAlias: live
      DeploymentPreference:
       Type: Linear10PercentEvery1Minute
  HelloWorldRDS:
      Type: 'AWS::RDS::DBCluster'
      Properties:
        DBClusterIdentifier: rds-sam-cluster
        Engine: aurora
        EngineVersion: 5.6.10a
        EngineMode: serverless
        MasterUsername: sam
        MasterUserPassword: sampassword1
        DatabaseName: sam
        ScalingConfiguration:
          AutoPause: true
          MinCapacity: 1
          MaxCapacity: 1
          SecondsUntilAutoPause: 300

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
